version: "3"
services:
  db:
    image: postgres:9.6
    environment:
      POSTGRES_USER: "fun"
      POSTGRES_PASSWORD: "pass"
    ports:
        - "5440:5432"
    volumes:
      - ./scripts/development/createdb.sh:/docker-entrypoint-initdb.d/createdb.sh:ro
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.1.2
  app:
    build: .
    environment:
      DATABASE_HOST: "db"
      DATABASE_USER: "fun"
      DATABASE_PASSWORD: "pass"
      ES_CLIENT: "elasticsearch"
    ports:
        - "8070:8000"
    volumes:
      - .:/app
      - ./data/static:/data/static
      - ./data/media:/data/media
    depends_on:
      - "db"
    ## Sleep 3 seconds while the database container is creating the database
    entrypoint: >
      bash -c "sleep 3 &&
      python manage.py collectstatic --no-input &&
      python manage.py runserver 0.0.0.0:8000"
  nginx:
    image: nginx:1.12.2
    ports:
      - "8071:80"
    volumes:
      - ./docker/etc/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./data/static:/data/static:ro
      - ./data/media:/data/media:ro
    depends_on:
      - "app"
  js:
    image: node:9.4.0
    volumes:
      - ./:/fun-cms
    entrypoint: >
      bash -c "npm install && webpack --watch"
  sass:
    image: ruby:2.4
    volumes:
      - ./:/fun-cms
    entrypoint: >
      bash -c "gem install sass &&
        mkdir -p /fun-cms/fun_cms/build/css &&
        sass --watch /fun-cms /fun-cms/fun_cms/static/scss/_main.scss:/fun-cms/fun_cms/build/css/main.css -E \"UTF-8\"";
    depends_on:
      - "js"
