version: "3"
services:
  db:
    image: postgres:9.6
    environment:
      POSTGRES_DB: "fun_cms"
      POSTGRES_USER: "fun"
      POSTGRES_PASSWORD: "pass"
    ports:
        - "5440:5432"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.1.2
  app:
    build: .
    environment:
      DATABASE_HOST: "db"
      DATABASE_USER: "fun"
      DATABASE_PASSWORD: "pass"
      ES_CLIENT: "elasticsearch"
    ports:
        - "8070:8000"
    volumes:
      - .:/app
      - ./data/static:/data/static
      - ./data/media:/data/media
    depends_on:
      - "db"
  nginx:
    image: nginx:1.12.2
    ports:
      - "8071:80"
    volumes:
      - ./docker/etc/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./data/static:/data/static:ro
      - ./data/media:/data/media:ro
    depends_on:
      - "app"
  node:
    image: node:9.4.0
    working_dir: /app
    volumes:
      - .:/app
