version: 2
jobs:

  build:
    docker:
      - image: python:3.6-stretch
    working_directory: ~/fun-cms
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v5-dependencies-{{ checksum "requirements/base.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v5-dependencies-
      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements/dev.txt
      - save_cache:
          paths:
            - ./venv
          key: v5-dependencies-{{ checksum "requirements/base.txt" }}

  lint-flake8:
    docker:
      - image: python:3.6-stretch
    working_directory: ~/fun-cms
    steps:
      - checkout
      - restore_cache:
          keys:
          - v5-dependencies-{{ checksum "requirements/base.txt" }}
          - v5-dependencies-
      - run:
          name: Lint code with flake8
          command: |
            . venv/bin/activate
            flake8

  lint-pylint:
    docker:
      - image: python:3.6-stretch
    working_directory: ~/fun-cms
    steps:
      - checkout
      - restore_cache:
          keys:
          - v5-dependencies-{{ checksum "requirements/base.txt" }}
          - v5-dependencies-
      - run:
          name: Lint code with pylint
          command: |
            . venv/bin/activate
            pylint apps plugins fun_cms

  test:
    docker:
      - image: python:3.6-stretch
        environment:
          DJANGO_SETTINGS_MODULE: 'fun_cms.settings'
          DJANGO_CONFIGURATION: 'ContinuousIntegration'
          DJANGO_SECRET_KEY: 'ThisIsAnExampleKeyForCIPurposeOnly'
          POSTGRES_HOST: '127.0.0.1'
          POSTGRES_DB: 'postgres'
          POSTGRES_USER: 'postgres'
          POSTGRES_PASSWORD: ''
      - image: postgres:9.6
      - image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.1.2
    working_directory: ~/fun-cms
    steps:
      - checkout
      - restore_cache:
          keys:
          - v5-dependencies-{{ checksum "requirements/base.txt" }}
          - v5-dependencies-
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            pytest

workflows:
  version: 2

  fun_cms:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - lint-flake8:
          requires:
            - build
          filters:
            tags:
              only: /.*/
      - lint-pylint:
          requires:
            - build
          filters:
            tags:
              only: /.*/
      - test:
          requires:
            - build
          filters:
            tags:
              only: /.*/
