version: 2
jobs:

  build:
    docker:
      - image: circleci/python:3.6.1
    working_directory: ~/fun-cms
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "app/requirements/dev.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r app/requirements/dev.txt
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "app/requirements/dev.txt" }}

  lint:
    docker:
      - image: circleci/python:3.6.1
    working_directory: ~/fun-cms
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "app/requirements/dev.txt" }}
          - v1-dependencies-
      - run:
          name: Lint code
          command: |
            . venv/bin/activate
            flake8

  test:
    docker:
      - image: circleci/python:3.6.1
        environment:
          DJANGO_SETTINGS_MODULE: 'fun_cms.settings.ci'
      - image: circleci/postgres:9.6
    working_directory: ~/fun-cms
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "app/requirements/dev.txt" }}
          - v1-dependencies-
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            pytest

workflows:
  version: 2

  fun_cms:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - lint:
          requires:
            - build
          filters:
            tags:
              only: /.*/
      - test:
          requires:
            - lint
          filters:
            tags:
              only: /.*/
